package main

import (
	"go_swagger/controllers"
	"go_swagger/database"
	_ "go_swagger/docs" // docs is generated by Swag CLI, you have to import it

	"github.com/gin-gonic/gin"
	"github.com/swaggo/gin-swagger"
	"github.com/swaggo/gin-swagger/swaggerFiles"
)

// @title Swagger Example API
// @version 1.0
// @description This is a sample server for people.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8081
// @BasePath /api/v1
func main() {
	// init
	database.Migrate()
	router := gin.Default()
	routes(router.Group("api/v1"))
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	router.Run(":8081")
}

func routes(v1 *gin.RouterGroup) {
	controller.PeopleRouting(v1.Group("people"))
}
